name: subjects
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: israelhudson <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  rxdart: ^0.21.0
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
